### ISSUE TITLE
[Unhandled promise rejection: TypeError: Network request failed]

### ISSUE THREAD

**Issue by snehadange** [myntra/ecommerce-demo#2]
Error: Possible Unhandled Promise Rejection (id: 0): TypeError: Network Request failed

**Comment by paramaggarwal** [comment]
The Myntra APIs used in this project are no longer publicly available.

**Comment by anuragdadheech** [comment]
Will update soon

**Comment by anuragdadheech** [comment]
Updated to a dummy API now as Myntra APIs are not externally accessible.
